### PR TITLE
Correct and rework requires interface. Remove unused code.

### PR DESCRIPTION
**Pull request by stub42**
Backwards incompatible changes, so hopefully not too many people are trying to use the current implementation. The old interface was very limited and only useful for simple charms needing a single non-replicated data source. Real systems need replication and multiple data silos for scale out.

### CODE REVIEW

**Comment by stub42** [comment]
This supersedes https://github.com/bcsaller/juju-relation-pgsql/pull/3

**Comment by stub42** [comment]
FWIW, charms using the current interface are not suitable for production deploys as they fail as soon as a second PostgreSQL is added, so no redundancy or simple scale out. It also doesn't support multiple data silos (a charm with multiple pgsql relations), nor sharding (where you have 1..n PostgreSQL services related)

**Comment by bcsaller** [comment]
This was only ever an example. I suggest we move the repo to one you own,
are you ok with that?

**Comment by stub42** [comment]
Sure. I'll put it in a new home and update the interfaces registry.

**Pull request closed without merging**
